<?php
	$PAGE_NAME = '';
	require_once($_SERVER["DOCUMENT_ROOT"].'/javascript/javascripthead.php');
?>
<main>
	<section>
		<p></p>
	</section>
	<section>
		<h4>:</h4>
		<p></p>
		<dl>
			<dt><code></code></dt>
			<dd></dd>
		</dl>
	</section>
</main>	
<?php
	require_once($_SERVER["DOCUMENT_ROOT"].'/genericfoot.php');
?>
